import { I18nSchema, Role, ActionType, Language } from './types';

export const INITIAL_COINS = 2;
export const MAX_PLAYERS = 6;
export const MIN_PLAYERS = 2;

export const ROLES_DECK = [
  Role.DUKE, Role.DUKE, Role.DUKE,
  Role.ASSASSIN, Role.ASSASSIN, Role.ASSASSIN,
  Role.CAPTAIN, Role.CAPTAIN, Role.CAPTAIN,
  Role.AMBASSADOR, Role.AMBASSADOR, Role.AMBASSADOR,
  Role.CONTESSA, Role.CONTESSA, Role.CONTESSA
];

export const I18N: Record<Language, I18nSchema> = {
  en: {
    lobby: {
      title: "COUP",
      create: "Create Room",
      join: "Join Room",
      enterName: "Enter your name",
      roomCode: "Room Code",
      waiting: "Waiting for host to start...",
      waitingForPlayers: "Waiting for more players...",
      youCanStart: "You can start the game.",
      startGame: "Start Game",
      needPlayers: "Need at least 2 players",
      players: "Players",
      host: "HOST"
    },
    game: {
      round: "Round",
      turn: "Turn",
      coins: "Coins",
      cards: "Cards",
      logs: "Game Log",
      dead: "Eliminated",
      you: "YOU",
      target: "Select Target",
      winner: "Winner!",
      actionRequired: "Your Action Required",
      loseCard: "You must lose an influence",
      returnTwoCards: "Return 2 cards",
      mustCoup: "You must Coup (10+ coins)",
      playAgain: "Play Again",
      playAgainHostOnly: "Play Again (host only)",
      exitGame: "Exit"
    },
    actions: {
      [ActionType.INCOME]: "Income (+1)",
      [ActionType.FOREIGN_AID]: "Foreign Aid (+2)",
      [ActionType.TAX]: "Tax (+3)",
      [ActionType.COUP]: "Coup (-7)",
      [ActionType.ASSASSINATE]: "Assassinate (-3)",
      [ActionType.STEAL]: "Steal (2)",
      [ActionType.EXCHANGE]: "Exchange",
      [ActionType.BLOCK_FOREIGN_AID]: "Block (Duke)",
      [ActionType.BLOCK_ASSASSINATE]: "Block (Contessa)",
      [ActionType.BLOCK_STEAL]: "Block (Captain/Ambassador)",
      [ActionType.CHALLENGE]: "Challenge",
      [ActionType.PASS]: "Pass"
    },
    roles: {
      [Role.DUKE]: "Duke",
      [Role.ASSASSIN]: "Assassin",
      [Role.CAPTAIN]: "Captain",
      [Role.AMBASSADOR]: "Ambassador",
      [Role.CONTESSA]: "Contessa"
    },
    status: {
      waiting: "Waiting for action...",
      challenging: "Challenge or Block",
      blocking: "Challenge block or Pass",
      resolving: "Resolving...",
      exchangeSelect: "Choose 2 cards to return to deck",
    },
    prompt: {
      respond: "Respond",
      doNotBlock: "Do not block",
      needCoins: "Need {n} coins",
      noValidTarget: "No valid target",
      deckTooSmall: "Deck too small (need 2)",
      cardLost: "Card lost",
      confirm: "Confirm",
      cancel: "Cancel",
      chooseCardToLose: "Choose a card to lose",
      usesAction: "uses",
      blockedYourAction: "blocked your action!",
      claimTheyLie: "Claim they lie",
      acceptBlock: "Accept block",
    },
    actionsShort: {
      [ActionType.INCOME]: "Income (+1)",
      [ActionType.FOREIGN_AID]: "Aid (+2)",
      [ActionType.TAX]: "Tax (+3)",
      [ActionType.STEAL]: "Steal",
      [ActionType.ASSASSINATE]: "Assassinate (-3)",
      [ActionType.COUP]: "Coup (-7)",
      [ActionType.EXCHANGE]: "Exchange",
    },
    log: {
      game_start: "Game started.",
      game_over: "Game Over! {winner} wins!",
      income_used: "{actor} used Income.",
      coup: "{actor} coups {target}.",
      action_attempt: "{actor} attempts {action}.",
      action_attempt_target: "{actor} attempts {action} on {target}.",
      block: "{blocker} blocks with {role}.",
      block_accepted: "Block accepted. Action failed.",
      steal_success: "{actor} took {amount} from {target}.",
      tax_success: "{actor} used Tax.",
      foreign_aid_success: "{actor} used Foreign Aid.",
      exchange_start: "{actor} exchanges. Choose 2 cards to return.",
      exchange_done: "{actor} completed exchange.",
      challenge_fail: "Challenge failed! {actor} had {role}. {loser} loses influence.",
      challenge_success_actor: "Challenge successful! {actor} did not have the role.",
      challenge_success_actor_loser: "Challenge successful! {actor} did not have the role. {loser} loses influence.",
      challenge_success_block_assassinate: "Challenge successful! {blocker} lied. Assassinate succeeds.",
      challenge_success_block_action: "Challenge successful! {blocker} lied. Action succeeds.",
      assassinate_victim: "{target} must lose influence.",
      unknown_event: "—",
    },
  },
  zh: {
    lobby: {
      title: "政变风云",
      create: "创建房间",
      join: "加入房间",
      enterName: "输入昵称",
      roomCode: "房间号",
      waiting: "等待房主开始...",
      waitingForPlayers: "等待更多玩家...",
      youCanStart: "您可以开始游戏",
      startGame: "开始游戏",
      needPlayers: "至少需要2名玩家",
      players: "玩家列表",
      host: "房主"
    },
    game: {
      round: "回合",
      turn: "当前回合",
      coins: "金币",
      cards: "手牌",
      logs: "游戏记录",
      dead: "已淘汰",
      you: "你",
      target: "选择目标",
      winner: "获胜者!",
      actionRequired: "请执行操作",
      loseCard: "你必须弃掉一张手牌",
      returnTwoCards: "放回2张牌",
      mustCoup: "10枚以上金币必须政变",
      playAgain: "再来一局",
      playAgainHostOnly: "再来一局（仅房主）",
      exitGame: "退出"
    },
    actions: {
      [ActionType.INCOME]: "收入 (+1)",
      [ActionType.FOREIGN_AID]: "外援 (+2)",
      [ActionType.TAX]: "税收 (+3)",
      [ActionType.COUP]: "政变 (-7)",
      [ActionType.ASSASSINATE]: "暗杀 (-3)",
      [ActionType.STEAL]: "偷窃 (2)",
      [ActionType.EXCHANGE]: "交换",
      [ActionType.BLOCK_FOREIGN_AID]: "阻挡 (公爵)",
      [ActionType.BLOCK_ASSASSINATE]: "阻挡 (伯爵夫人)",
      [ActionType.BLOCK_STEAL]: "阻挡 (队长/大使)",
      [ActionType.CHALLENGE]: "质疑",
      [ActionType.PASS]: "过"
    },
    roles: {
      [Role.DUKE]: "公爵",
      [Role.ASSASSIN]: "刺客",
      [Role.CAPTAIN]: "队长",
      [Role.AMBASSADOR]: "大使",
      [Role.CONTESSA]: "伯爵夫人"
    },
    status: {
      waiting: "等待行动...",
      challenging: "质疑或阻挡",
      blocking: "质疑阻挡或过",
      resolving: "结算中...",
      exchangeSelect: "选择2张牌放回牌堆",
    },
    prompt: {
      respond: "轮到你回应",
      doNotBlock: "不阻挡",
      needCoins: "需要{n}枚金币",
      noValidTarget: "无有效目标",
      deckTooSmall: "牌堆不足（需2张）",
      cardLost: "已弃牌",
      confirm: "确认",
      cancel: "取消",
      chooseCardToLose: "选择一张牌弃掉",
      usesAction: "使用",
      blockedYourAction: "阻挡了你的行动！",
      claimTheyLie: "质疑（声称撒谎）",
      acceptBlock: "接受阻挡",
    },
    actionsShort: {
      [ActionType.INCOME]: "收入 (+1)",
      [ActionType.FOREIGN_AID]: "外援 (+2)",
      [ActionType.TAX]: "税收 (+3)",
      [ActionType.STEAL]: "偷窃",
      [ActionType.ASSASSINATE]: "暗杀 (-3)",
      [ActionType.COUP]: "政变 (-7)",
      [ActionType.EXCHANGE]: "交换",
    },
    log: {
      game_start: "游戏开始。",
      game_over: "游戏结束！{winner} 获胜！",
      income_used: "{actor} 使用了收入。",
      coup: "{actor} 对 {target} 发动政变。",
      action_attempt: "{actor} 尝试 {action}。",
      action_attempt_target: "{actor} 对 {target} 尝试 {action}。",
      block: "{blocker} 用 {role} 阻挡。",
      block_accepted: "阻挡成功。行动失败。",
      steal_success: "{actor} 从 {target} 处拿走了 {amount} 枚金币。",
      tax_success: "{actor} 使用了税收。",
      foreign_aid_success: "{actor} 使用了外援。",
      exchange_start: "{actor} 交换手牌。请选择2张牌放回。",
      exchange_done: "{actor} 完成交换。",
      challenge_fail: "质疑失败！{actor} 拥有 {role}。{loser} 失去影响力。",
      challenge_success_actor: "质疑成功！{actor} 没有该角色。",
      challenge_success_actor_loser: "质疑成功！{actor} 没有该角色。{loser} 失去影响力。",
      challenge_success_block_assassinate: "质疑成功！{blocker} 撒谎。暗杀生效。",
      challenge_success_block_action: "质疑成功！{blocker} 撒谎。行动生效。",
      assassinate_victim: "{target} 必须失去影响力。",
      unknown_event: "—",
    },
  }
};